/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    'nav.products': 'Products',
    'nav.orders': 'Orders',
    'nav.login': 'Sign In',
    'nav.logout': 'Logout',
    
    'home.hero.title': 'The Ultimate PC Experience',
    'home.hero.subtitle': 'Build your dream setup with top-tier hardware.',
    'home.hero.cta': 'Shop Now',
    'home.browse': 'Browse Categories',
    'home.recommended': 'Recommended for You',
    'home.viewAll': 'View All',
    'home.price': 'Price',
    'cat.graphicsCards': 'Graphics Cards',
    'cat.processors': 'Processors',
    'cat.memory': 'Memory',
    'cat.motherboards': 'Motherboards',
    
    'products.title': 'All Hardware',
    'products.search': 'Search products...',
    'products.brand': 'Brand',
    'products.maxPrice': 'Max Price',
    'products.reset': 'Reset Filters',
    'products.noFound': 'No products found',
    'products.filters': 'Filters',
    'products.sortBy': 'Sort by:',
    'products.sortDefault': 'Default',
    'products.sortLowHigh': 'Price: Low to High',
    'products.sortHighLow': 'Price: High to Low',
    
    'orders.title': 'Order History',
    'orders.id': 'Order ID',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.item': 'Item',
    'orders.qty': 'Qty',
    'orders.status': 'Status',
    'orders.viewInvoice': 'View Invoice',
    
    'invoice.title': 'INVOICE',
    'invoice.billTo': 'Bill To:',
    'invoice.subtotal': 'Subtotal:',
    'invoice.tax': 'Tax (7%):',
    'invoice.grandTotal': 'Grand Total:',
    'invoice.print': 'Print Invoice',
    'invoice.close': 'Close',

    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.customers': 'Customers',
    'admin.totalSales': 'Total Sales',
    'admin.totalOrders': 'Total Orders',
    'admin.totalCustomers': 'Total Customers',
    'admin.activeProducts': 'Active Products',
    'admin.salesChart': 'Sales Overview',
    'admin.recentOrders': 'Recent Orders',
    'admin.productName': 'Product Name',
    'admin.category': 'Category',
    'admin.price': 'Price',
    'admin.stock': 'Stock',
    'admin.actions': 'Actions',
    'admin.customerName': 'Customer Name',
    'admin.email': 'Email',
    'admin.date': 'Date',
    'admin.spent': 'Total Spent',
    'admin.addProduct': 'Add Product',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.exportReport': 'Export Report',
    'admin.cancel': 'Cancel',
    'admin.save': 'Save',
    'admin.imageUrl': 'Image URL',
    'admin.editProduct': 'Edit Product',
    'admin.editOrder': 'Edit Order',
    'admin.addCustomer': 'Add Customer',
    'admin.editCustomer': 'Edit Customer',
    'admin.status': 'Status',

    'product.loading': 'Loading product...',
    'product.notFound': 'Product not found',
    'product.back': 'Back to Products',
    'product.reviews': 'Reviews',
    'product.addedToCart': 'Added to Cart',
    'product.addToCart': 'Add to Cart',
    'product.warranty': '3 Year Warranty',
    'product.distributor': 'Official Distributor',
    'product.shipping': 'Free Shipping',
    'product.shippingTime': '2-3 Business Days',
    'product.techSpecs': 'Technical Specifications',
    'product.category': 'Category',
    'product.brandLabel': 'Brand',
    'product.memoryLabel': 'Memory / Capacity',
    'product.features': 'Key Features',

    'cart.title': 'Your Cart',
    'cart.empty': 'Your Cart is Empty',
    'cart.checkout': 'Confirm Payment',
    'cart.startShopping': 'Start Shopping',

    'checkout.title': 'Checkout',
    'checkout.orderItems': 'Order Items',
    'checkout.qty': 'Qty',
    'checkout.remove': 'Remove',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.postalCode': 'Postal Code',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.creditCard': 'Credit Card',
    'checkout.qrPromptPay': 'QR PromptPay',
    'checkout.cardNumber': 'Card Number',
    'checkout.expiryDate': 'Expiry Date',
    'checkout.cvc': 'CVC',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.tax': 'Estimated Tax (7%)',
    'checkout.total': 'Total',
    'checkout.free': 'Free',
    'checkout.processing': 'Processing...',
    'checkout.confirmPayment': 'Confirm Payment',
    'checkout.terms': 'By confirming, you agree to our Terms of Service and Privacy Policy.',

    'nav.builder': 'Custom PC',
    'builder.title': 'Custom PC Builder',
    'builder.preview': 'Preview',
    'builder.noSelection': 'No part selected yet',
    'builder.total': 'Total Price',
    'builder.addCart': 'Add All to Cart',
    'builder.selectPrompt': 'Please select a component from the list below.',
    'builder.addingSoon': 'We are adding more products soon.',
    'builder.spec': 'Spec',
    'cat.cpu': 'CPU',
    'cat.mobo': 'Motherboard',
    'cat.gpu': 'VGA / GPU',
    'cat.ram': 'RAM',
    'cat.hdd': 'Hard Disk',
    'cat.ssd': 'Solid State Drive (SSD)',
    'cat.m2': 'M.2 Card',
    'cat.psu': 'Power Supply',
    'cat.case': 'Case',
    'cat.cooler': 'Liquid Cooling',
    'cat.aircooler': 'CPU Air Cooler',
    'cat.fan': 'Case Fan',
    'cat.mouse': 'Mouse',
    'cat.keyboard': 'Keyboard',
    'cat.monitor': 'Monitor',
    'cat.accessories': 'Accessories',
    'cat.gear': 'Gaming Gear',
    'cat.software': 'Software',
    
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to manage your orders and checkout.',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.forgot': 'Forgot?',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',
    'login.google': 'Login with Google',
    'login.noAccount': 'Don\'t have an account?',
    'login.signup': 'Sign up',
    
    'register.title': 'Register',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.phone': 'Phone Number',
    'register.dob': 'Date of Birth',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.submit': 'Sign Up',
    'register.submitting': 'Processing...',
    'register.hasAccount': 'Already have an account?',
    'register.signin': 'Sign In',
  },
  th: {
    'nav.products': 'สินค้าทั้งหมด',
    'nav.orders': 'ประวัติสั่งซื้อ',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.logout': 'ออกจากระบบ',
    
    'home.hero.title': 'สุดยอดประสบการณ์คอมพิวเตอร์',
    'home.hero.subtitle': 'จัดสเปคในฝันด้วยฮาร์ดแวร์ระดับท็อป',
    'home.hero.cta': 'เลือกซื้อเลย',
    'home.browse': 'เลือกดูตามหมวดหมู่',
    'home.recommended': 'สินค้าแนะนำสำหรับคุณ',
    'home.viewAll': 'ดูทั้งหมด',
    'home.price': 'ราคา',
    'cat.graphicsCards': 'การ์ดจอ',
    'cat.processors': 'ซีพียู',
    'cat.memory': 'แรม',
    'cat.motherboards': 'เมนบอร์ด',
    
    'products.title': 'อุปกรณ์ทั้งหมด',
    'products.search': 'ค้นหาสินค้า...',
    'products.brand': 'แบรนด์',
    'products.maxPrice': 'ราคาสูงสุด',
    'products.reset': 'ล้างตัวกรอง',
    'products.noFound': 'ไม่พบสินค้า',
    'products.filters': 'ตัวกรอง',
    'products.sortBy': 'เรียงตาม:',
    'products.sortDefault': 'ค่าเริ่มต้น',
    'products.sortLowHigh': 'ราคา: ต่ำไปสูง',
    'products.sortHighLow': 'ราคา: สูงไปต่ำ',
    
    'orders.title': 'ประวัติคำสั่งซื้อ',
    'orders.id': 'รหัสคำสั่งซื้อ',
    'orders.date': 'วันที่',
    'orders.total': 'ยอดรวม',
    'orders.item': 'สินค้า',
    'orders.qty': 'จำนวน',
    'orders.status': 'สถานะ',
    'orders.viewInvoice': 'ดูใบเสร็จ',
    
    'invoice.title': 'ใบเสร็จรับเงิน',
    'invoice.billTo': 'ออกให้แก่:',
    'invoice.subtotal': 'ยอดรวม (ก่อนภาษี):',
    'invoice.tax': 'ภาษีมูลค่าเพิ่ม (7%):',
    'invoice.grandTotal': 'ยอดรวมทั้งสิ้น:',
    'invoice.print': 'พิมพ์ใบเสร็จ',
    'invoice.close': 'ปิด',

    'admin.title': 'ระบบจัดการหลังบ้าน',
    'admin.overview': 'ภาพรวม',
    'admin.products': 'สินค้า',
    'admin.orders': 'คำสั่งซื้อ',
    'admin.customers': 'ลูกค้า',
    'admin.totalSales': 'ยอดขายรวม',
    'admin.totalOrders': 'จำนวนคำสั่งซื้อ',
    'admin.totalCustomers': 'จำนวนลูกค้า',
    'admin.activeProducts': 'สินค้าที่วางขาย',
    'admin.salesChart': 'กราฟยอดขาย',
    'admin.recentOrders': 'คำสั่งซื้อล่าสุด',
    'admin.productName': 'ชื่อสินค้า',
    'admin.category': 'หมวดหมู่',
    'admin.price': 'ราคา',
    'admin.stock': 'สถานะคลัง',
    'admin.actions': 'จัดการ',
    'admin.customerName': 'ชื่อลูกค้า',
    'admin.email': 'อีเมล',
    'admin.date': 'วันที่',
    'admin.spent': 'ยอดซื้อสะสม',
    'admin.addProduct': 'เพิ่มสินค้า',
    'admin.edit': 'แก้ไข',
    'admin.delete': 'ลบ',
    'admin.exportReport': 'ส่งออกรายงาน',
    'admin.cancel': 'ยกเลิก',
    'admin.save': 'บันทึก',
    'admin.imageUrl': 'ลิงก์รูปภาพ',
    'admin.editProduct': 'แก้ไขสินค้า',
    'admin.editOrder': 'อัปเดตคำสั่งซื้อ',
    'admin.addCustomer': 'เพิ่มลูกค้า',
    'admin.editCustomer': 'แก้ไขลูกค้า',
    'admin.status': 'สถานะ',

    'product.loading': 'กำลังโหลดข้อมูลสินค้า...',
    'product.notFound': 'ไม่พบสินค้า',
    'product.back': 'กลับไปหน้ารวมสินค้า',
    'product.reviews': 'รีวิว',
    'product.addedToCart': 'เพิ่มลงตะกร้าแล้ว',
    'product.addToCart': 'เพิ่มลงตะกร้า',
    'product.warranty': 'รับประกัน 3 ปี',
    'product.distributor': 'ตัวแทนจำหน่ายอย่างเป็นทางการ',
    'product.shipping': 'จัดส่งฟรี',
    'product.shippingTime': '2-3 วันทำการ',
    'product.techSpecs': 'ข้อมูลจำเพาะทางเทคนิค',
    'product.category': 'หมวดหมู่',
    'product.brandLabel': 'แบรนด์',
    'product.memoryLabel': 'หน่วยความจำ / ความจุ',
    'product.features': 'คุณสมบัติเด่น',

    'cart.title': 'ตะกร้าสินค้า',
    'cart.empty': 'ตะกร้าสินค้าของคุณว่างเปล่า',
    'cart.checkout': 'ยืนยันการชำระเงิน',
    'cart.startShopping': 'เริ่มเลือกซื้อสินค้า',

    'checkout.title': 'ชำระเงิน',
    'checkout.orderItems': 'รายการสินค้า',
    'checkout.qty': 'จำนวน',
    'checkout.remove': 'ลบ',
    'checkout.shippingInfo': 'ข้อมูลการจัดส่ง',
    'checkout.firstName': 'ชื่อ',
    'checkout.lastName': 'นามสกุล',
    'checkout.address': 'ที่อยู่',
    'checkout.city': 'เมือง/จังหวัด',
    'checkout.postalCode': 'รหัสไปรษณีย์',
    'checkout.paymentMethod': 'วิธีการชำระเงิน',
    'checkout.creditCard': 'บัตรเครดิต',
    'checkout.qrPromptPay': 'คิวอาร์พร้อมเพย์',
    'checkout.cardNumber': 'หมายเลขบัตร',
    'checkout.expiryDate': 'วันหมดอายุ',
    'checkout.cvc': 'CVC',
    'checkout.orderSummary': 'สรุปคำสั่งซื้อ',
    'checkout.subtotal': 'ยอดรวม',
    'checkout.shipping': 'ค่าจัดส่ง',
    'checkout.tax': 'ภาษีมูลค่าเพิ่ม (7%)',
    'checkout.total': 'ยอดรวมทั้งสิ้น',
    'checkout.free': 'ฟรี',
    'checkout.processing': 'กำลังดำเนินการ...',
    'checkout.confirmPayment': 'ยืนยันการชำระเงิน',
    'checkout.terms': 'การยืนยันคำสั่งซื้อถือว่ายอมรับข้อกำหนดการให้บริการและนโยบายความเป็นส่วนตัวของเรา',

    'nav.builder': 'จัดสเปคคอม',
    'builder.title': 'จัดสเปคคอมพิวเตอร์',
    'builder.preview': 'ดูตัวอย่าง',
    'builder.noSelection': 'ยังไม่ได้เลือกอุปกรณ์',
    'builder.total': 'ยอดรวมทั้งสิ้น',
    'builder.addCart': 'เพิ่มสเปคลงตะกร้า',
    'builder.selectPrompt': 'โปรดเลือกอุปกรณ์จากรายการด้านล่าง',
    'builder.addingSoon': 'เรากำลังเพิ่มสินค้าเพิ่มเติมเร็วๆ นี้',
    'builder.spec': 'สเปค',
    'cat.cpu': 'ซีพียู',
    'cat.mobo': 'เมนบอร์ด',
    'cat.gpu': 'การ์ดจอ',
    'cat.ram': 'แรม',
    'cat.hdd': 'ฮาร์ดดิสก์',
    'cat.ssd': 'โซลิดสเตตไดรฟ์ (เอสเอสดี)',
    'cat.m2': 'การ์ด M.2',
    'cat.psu': 'พาวเวอร์ซัพพลาย',
    'cat.case': 'เคส',
    'cat.cooler': 'ชุดน้ำปิด',
    'cat.aircooler': 'พัดลมซีพียู',
    'cat.fan': 'พัดลมเคส',
    'cat.mouse': 'เมาส์',
    'cat.keyboard': 'คีย์บอร์ด',
    'cat.monitor': 'จอมอนิเตอร์',
    'cat.accessories': 'อุปกรณ์เสริม',
    'cat.gear': 'เกมมิ่งเกียร์',
    'cat.software': 'ซอฟต์แวร์',
    
    'login.title': 'ยินดีต้อนรับกลับมา',
    'login.subtitle': 'เข้าสู่ระบบเพื่อจัดการคำสั่งซื้อและการชำระเงิน',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.forgot': 'ลืมรหัสผ่าน?',
    'login.submit': 'เข้าสู่ระบบ',
    'login.submitting': 'กำลังเข้าสู่ระบบ...',
    'login.google': 'เข้าสู่ระบบด้วย Google',
    'login.noAccount': 'ยังไม่มีบัญชีผู้ใช้?',
    'login.signup': 'สมัครสมาชิก',
    
    'register.title': 'ลงทะเบียน',
    'register.firstName': 'ชื่อ',
    'register.lastName': 'นามสกุล',
    'register.phone': 'เบอร์โทรศัพท์',
    'register.dob': 'วันเกิด',
    'register.email': 'อีเมล',
    'register.password': 'รหัสผ่าน',
    'register.confirmPassword': 'ยืนยันรหัสผ่าน',
    'register.submit': 'สมัครสมาชิก',
    'register.submitting': 'กำลังดำเนินการ...',
    'register.hasAccount': 'มีบัญชีผู้ใช้แล้ว?',
    'register.signin': 'เข้าสู่ระบบ',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('th');

  const toggleLanguage = () => {
    setLang(prev => prev === 'en' ? 'th' : 'en');
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
